### ISSUE TITLE
UserModel.Class.Php 是不是少了Add 方法

### ISSUE THREAD

**Issue by momomoQ1** [vincenth520/pinche_xcx_data#1]
在 下面Login() 中 有个         $u->add($UserInfo);  需要用到这个方法？

    public function login(){   
        $sk = $this->getOpenid(I('code'));

        $u = D('User');
        $user = $u->getUserInfo($sk['openid']);
        if(empty($user)){ //如果第一次登陆
            $UserInfo = json_decode($this->getUserInfo($sk['session_key'],I('encryptedData'),I('iv')),true);
            unset($UserInfo['watermark']);
        

    $u->add($UserInfo);

        }
        $user = $u->getUserInfo($sk['openid']);
        $sk = $this->get3rdSession($sk['openid'],$sk['session_key']);
        $result['user'] = $user;
        $result['sk'] = $sk;
        exit(json_encode($result));
    }

**Comment by vincenth520** [comment]
model类自带的add方法
